@Lab.Demo.Gateway_HostAddress = https://localhost:7000

GET {{Lab.Demo.Gateway_HostAddress}}/api/products/
Accept: application/json

###


GET {{Lab.Demo.Gateway_HostAddress}}/api/orders/
Accept: application/json

###
